### PR TITLE
Increment version

### PR DESCRIPTION
**Pull request by kbattersby**
Increment version after table support changes. 

[EREZ-678](https://erezlife.atlassian.net/browse/EREZ-678)

[EREZ-678]: https://erezlife.atlassian.net/browse/EREZ-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EREZ-678]: https://erezlife.atlassian.net/browse/EREZ-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by AlbertRothman — COMMENTED** [review]
Does this do anything functional or just indicate what version we are on? If it doesn't do anything functional, then I don't find the commit completely clear. I'd shorten the subject to "Increment version" and then include the details about table support in the message.

**Comment by kbattersby** [comment]
This particular commit for this PR right here does nothing other than increment the version. But the reason I want to increment the version is so that the table support changes can be released. 
https://github.com/erezlife/html2docx/pull/77#issuecomment-1338978306

**Comment by AlbertRothman** [comment]
Thanks for the PR changes; looking at the commit history, it doesn't look like we use bors on this repo. Thus we need to change the actual commit message and comment not just the title and first comment on github. 

Before merging this, I also wonder if we want to clean up the commit history for the last PR that landed multiple commits at once. I think this should be fine since it's pre-release, but maybe it's safer to just keep the extra commits. Thoughts?

**Comment by kbattersby** [comment]
> Thanks for the PR changes; looking at the commit history, it doesn't look like we use bors on this repo. Thus we need to change the actual commit message and comment not just the title and first comment on github.
> 
> Before merging this, I also wonder if we want to clean up the commit history for the last PR that landed multiple commits at once. I think this should be fine since it's pre-release, but maybe it's safer to just keep the extra commits. Thoughts?

Changed the name of the commit message. However since the previous commits have landed on master, I think it's better to just leave them as they are, but going forward to keep the commits clean.

**Review by AlbertRothman — APPROVED** [review]

**Pull request merged**
